<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>FlakyTestRunner.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">OpenHFT/Chronicle-Core</a> &gt; <a href="index.source.html" class="el_package">net.openhft.chronicle.core</a> &gt; <span class="el_source">FlakyTestRunner.java</span></div><h1>FlakyTestRunner.java</h1><pre class="source lang-java linenums">package net.openhft.chronicle.core;

import net.openhft.chronicle.core.onoes.Slf4jExceptionHandler;

<span class="fc" id="L5">public enum FlakyTestRunner {</span>
    ;

<span class="fc" id="L8">    static boolean IN_RUN = false;</span>

    public static &lt;T extends Throwable&gt; void run(RunnableThrows&lt;T&gt; rt) throws T {
<span class="fc" id="L11">        run(true, rt);</span>
<span class="fc" id="L12">    }</span>

    public static &lt;T extends Throwable&gt; void run(boolean flakyOnThisArch, RunnableThrows&lt;T&gt; rt) throws T {
<span class="fc bfc" id="L15" title="All 2 branches covered.">        if (!flakyOnThisArch) {</span>
<span class="fc" id="L16">            rt.run();</span>
<span class="fc" id="L17">            return;</span>
        }
        try {
            // stop accidental call back to self.
<span class="pc bpc" id="L21" title="1 of 2 branches missed.">            if (IN_RUN)</span>
<span class="nc" id="L22">                throw new AssertionError(&quot;Can't run nested&quot;);</span>
<span class="fc" id="L23">            IN_RUN = true;</span>

<span class="fc" id="L25">            rt.run();</span>

<span class="nc" id="L27">        } catch (Throwable t) {</span>
<span class="nc" id="L28">            System.err.println(&quot;Rerunning failing test&quot;);</span>
<span class="nc" id="L29">            System.gc();</span>
<span class="nc" id="L30">            Jvm.pause(500);</span>
<span class="nc" id="L31">            rt.run();</span>
<span class="nc" id="L32">            Slf4jExceptionHandler.WARN.on(FlakyTestRunner.class, &quot;Flaky test threw an error the first run, passed the second time&quot;, t);</span>
        } finally {
<span class="fc" id="L34">            IN_RUN = false;</span>
        }
<span class="fc" id="L36">    }</span>

    public interface RunnableThrows&lt;T extends Throwable&gt; {
        void run() throws T;
    }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.6.202009150832</span></div></body></html>